### ISSUE TITLE
[BUG] Coloured water crashes the game on rendering with Colormatic

### ISSUE THREAD

**Issue by SplendidAlakey** [Exploding-Creeper/Hyper-Lighting#12] opened 2022-05-02 17:58 UTC
**Describe the bug**

Placing down coloured water will crash the game. Generating a chunk that has a coloured lake in it will crash the game. If Sodium+Indium are installed, then the game simply won't render the entire chunk that has the coloured water in it.

**To Reproduce:**

1. Install the mod and [Colormatic](https://www.curseforge.com/minecraft/mc-mods/colormatic), create a new world
2. If you are lucky, there won't be any coloured lakes generated near you and you will be able to spawn; otherwise, instant crash or fall through void indefinitely
3. If you managed to spawn without any lakes around you, just teleport or fly to a chunk that has a coloured lake; as soon as the chunk attempts to render, the game will crash
4. Alternatively, grab a bucket of coloured water from a creative inventory and right-click the ground anywhere

**Expected behavior**

Coloured water shouldn't crash the game.

**Versions (DO NOT USE "LATEST"! I STEAL YOUR KNEE CAPS!):**

 - Minecraft Version: 1.18.2
 - Modloader
 - [❌] Forge
 - [✅] Fabric
 - Mod Loader Version: 0.14.4
 - Mod Version: 1.2.2
 - RGBLib Version [If installed]: -
 - [✅] Client Side
 - [✅] Server Side

**Crash Report**

https://gist.github.com/Footage2-Amply-Pounce/13baea13f5b4e3993c370f1ac04581ad

**Comment by hypherionmc** [comment] 2022-05-02 18:03
Hmm interesting. Thanks for the report, I'll look into this. You should be able to disable colored water generation in the config for now

**Comment by SplendidAlakey** [comment] 2022-05-02 18:05
Yep, I always had it disabled, so not a big deal for me. I just happened to uncover the bug when dealing with another issue and resetting all my configs to default, which caused lakes to start generating.

**Comment by hypherionmc** [comment] 2022-05-03 09:06
I'm having one of my contributors look into this. I suspect the compat code we added for Optifine is causing problems with sodium

**Comment by hypherionmc** [comment] 2022-05-05 10:10
Just some feedback, we are able to reproduce the issue with just colormatic installed. Looking into what the cause is and getting it fixed

**Comment by SplendidAlakey** [comment] 2022-05-05 10:12
Yeah the crash happens with just Colormatic. Sodium actually prevents the crash by not rendering the chunk with coloured water in it at all for some reason.

**Comment by hypherionmc** [comment] 2022-05-05 10:19
Yeah I think sodium stops rendering chunks that have problems, to prevent performance issues

**Comment by hypherionmc** [comment] 2022-05-05 21:42
Okay for now this seems to be an issue with Colormatic itself. I have opened a bug report, so I'll update once I get feedback from them :)

For reference: [#94](https://github.com/kvverti/colormatic/issues/94)

**Comment by hypherionmc** [comment] 2022-06-08 07:09
Looks like Colormatic finally released a fix :) Closing this for now. If you still get this issue, feel free to re-open

**Closed as completed by hypherionmc** 2022-06-08 07:09 UTC
Labels: bug, bug in other software, fabric
